---
date: 2017-08-20
title: Misc
tags: ['literature']
output: blogdown::html_page
---

## Misc

### Cancer, chromatin loop and SVs

Chromatin loop anchor points (LAPs) as sites of regulatory importance but also genomic fragility.
They harbour an excess of SV breakpoints in cancers, are prone to double strand breaks in somatic cells, and are bound by DNA repair complex proteins.

[Kaiser & Semple bioRxiv 2017](http://www.biorxiv.org/content/early/2017/07/21/166934)

### TE suppression in cancer

TE suppression proposed as a mechanism for immune escape in acute myeloid leukaemia (AML) and myelodysplastic syndrome (MDS).
TE are less expressed in high-risk vs low-risk, or in resistant cancers.
Too much TE expressed would cause interferon signaling and cancer cell killing.

[Colombo et al Sci. Reports 2017](https://www.nature.com/articles/s41598-017-07356-9)


## R

### Hugo and Blogdown

I'm hearing more and more about [Hugo](https://gohugo.io/) website and [Blogdown](https://bookdown.org/yihui/blogdown/) seems to be the R package to build and manage one.

Why is Hugo better than Jekyll ?

- Faster apparently.
- Easier workflow, less things to install.
- Templates a much cooler.
- Seamless integration of RMarkdown (through Blogdown).

Blogdown was written by the same person who wrote knitr (Yihui Xie).
He also wrote [bookdown](https://github.com/rstudio/bookdown) and works at RStudio.

- [How to set up Hugo + Blogdown on GitHub Pages](https://talesofr.wordpress.com/2017/08/18/starting-a-rmarkdown-blog-with-bookdown-hugo-github/)


### dplyr tricks

Using `enquo` to enquote a variable and `!!` to unquote it.
[For example](https://www.enchufa2.es/archives/programming-with-dplyr-by-using-dplyr.html):

~~~R
starwars_mean <- function(var) {
  var <- enquo(var)
  starwars %>%
    group_by(!!var) %>%
    summarise(mean_height = mean(height, na.rm = TRUE),
            mean_mass = mean(mass, na.rm = TRUE),
            count = n())
}

starwars_mean(homeworld)
~~~

### Mix multiple graphs with ggplot2

Using the ggpubr functions, multi graphs panels can be produced, with aligned axis if needed.

[Tutorial](http://www.sthda.com/english/wiki/ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page)

### Joy Plots

Joy plots are several density curves horizontally aligned and overlapping each other slightly.
It's a cool way to visualize progression or gradually different profiles.
[Some examples](http://mran.microsoft.com/web/packages/ggjoy/vignettes/gallery.html) and a [R package](https://github.com/clauswilke/ggjoy).
