---
title: Single Cell RNA-seq and GBM
tags: ['literature']
date: 2017-05-23
output: blogdown::html_page
---

Three studies used single cell RNA-seq on brain cancer tumors. 
They also called large CNA from this data. 
How ?

## scRNA highlights intra-tumoral heterogeneity in primary glioblastoma

[Patel et al. (Science 2014)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4123637/)

- Intra-tumoral heterogeneity is thought to be an important factor of treatment resistance and relapses.
- GBM is one of the most lethal human malignancy.

They show that known **suptype** classifier for GBMs are **actually expressed** differently **across the cells** from the **same tumor**.

To infer large CNA they *averaged* the *relative expression* across large regions. 
They actually average the gene expression using a *sliding window* of 100 genes. 
Hence for each of the 6,000 expressed gene they compute this average expression and use it to *cluster cells*.
For the *heatmap*, the signal was normalized using the control (bulk RNA-seq from normal brain samples).

+ They profile 430 cells from 5 glioblastomas using SMART-seq.
+ They excluded genes and cells with low coverage. They ended up with ~6,000 genes.
+ They also have bulk RNA-seq from the tumor.

## scRNA supports developmental hierarchy in human oligodendroglioma

[Tirosh et al. (Nature 2016)](http://www.nature.com/nature/journal/v539/n7628/full/nature20123.html)

They used the **same approach** than in the previous study. 
However they normalized the expression of each gene by the average across cells of the same tumor. 
Then they *winsorized* these relative expression ([-3,3]) to limit the effect of outliers in the moving average estimation.

Here they didn't have normals as control so **they guessed which CNV-based cluster of cells were normal**: 

- *consistent* CNV patterns 
- higher values at 1p/19q which are known losses in this cancer.

## Decoupling genetics, lineages, and microenvironment in IDH-mutant gliomas by scRNA

[Venteicher et al. (Science 2017)](https://www.ncbi.nlm.nih.gov/pubmed/28360267)

Same lab, same idea.

scRNA QC:

1. Remove cells with less than 3000 expressed genes (at least one read).
1. Remove cells with average $$log_2(\frac{TPM}{10} + 1)$$ below 2.5 in housekeeping genes.
1. Remove genes with $$log_2(\bar{TPM}+1)$$ below 4.

Then the relative expression is the $$E_r = E - \bar{E}$$ for each gene, with $$E=log_2(\frac{TPM}{10} + 1) $$.

To identify normal cells they first performed a hierarchical clustering of all IDH-A cells and observed three clusters.
One of the cluster is suspected to be malignant cells.
For the CNVs they used the same approach as before but corrected it with two baselines derived from the two "normal" clusters.
So again, moving average of winsorized relative expression across 100 genes.
These values were corrected with the baseline as follows:

- 0 if $$BaseMin - 0.2 < CNV < BaseMax + 0.2$$
- $$ CNV - BaseMin $$ if $$CNV < BaseMin - 0.2$$
- $$ CNV - BaseMax $$ if $$CNV > BaseMax + 0.2$$

Two strategies were used to classify a cell as malignant:

1. If the correlation of the gene expression profile was at least 0.3 superior when comparing with the average profile of the "malignant" cluster compared to the other two..
1. If the "CNV signal" was higher than 0.05 and correlation with the CNVs in the "malignant" cluster was higher than 0.5.

A malignant cell was classified as malignant in both strategies or malignant in one and borderline in the other.


## Pooling and deconvoluting cells for normalization

I had an idea of merging cells into meta-cells to call CNVs.
That way the higher depth allows for a much higher resolution.

Lun, Bach & Marioni ([Genome Biology 2016](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0947-7)) developed a method using this strategy for normalization.

Their objective is to avoid problems created by the high number of genes with null (or extremely low) expression.
They merge cells and compute a normalization factor for each pool.
Then these estimations are deconvoluted to get a normalization factor for each cell.

The result of each pool is used to build a system of linear equations to resolve.

There are a few additional tricks (e.g. how to build the pools or cluster the genes) but the main idea and tools are interesting.
