---
date: 2017-04-09
title: Family-based designs for gene-association studies
tags: ['literature']
output: blogdown::html_page
---


Different type of family information can be used.
**Trio designs** (affected offspring plus parents) seems to have the most power but having both affected and unaffected siblings is useful too.

A positive result in a family-based test means there is both **linkage** and **association**.
It avoids problems with population stratification or admixture.


## Transmission Disequilibrium Test (TDT)

The TDT compares the number of observed allele transmitted to the affected offspring with the expected number following Mendelian transmission.
It is completely non-parametric in the sense that it doesn't require specifying a disease model.

In its simple form (complete trios), the TDT is more or less a Binomial test on the number of transmitted allele according to the number of heterozygous parents.
It cannot deal with missing parents or more general pedigrees.


## Family-Based Association Tests (FBATs)

An extension of the TDT.

The FBAT statistic represents how the observed genotype diverges from the expected genotype in individuals with phenotype:

$$ U = \sum T * (X-E(X|P)) $$

with the sum being over all offspring and 

- $$T=Y-\mu$$ the centered phenotype
- $$X$$ the genotype
- \\(E(X\|P)\\) the expected genotype.

The FBAT statistics is $$\frac{U^2}{Var(U)}$$ and follows a $$\chi^2$$ distribution with one degree of freedom (if at least 10 families).

- The genotype $$X$$ can be coded to reflect the mode of inheritance.
- Both \\(E(X\|P)\\) and $$Var(U)$$ are computed under the null hypothesis from the parents/siblings genotypes.

*TODO empirical estimate of the variance from Lake et al 2000.*


## Filtering variants

Another approach is to focus on (homozygous) segregating variants and annotate them to assess their functional impact (frequency, location).

## References

- [*Family-based designs in the age of large-scale gene-association studies.* by Laird & Lange (Nature Reviews Genetics 2006)](https://www.ncbi.nlm.nih.gov/pubmed/16619052)
- [*Family-Based Tests of Association in the Presence of Linkage.* by Lake et al. (AJHG 200)](http://www.ncbi.nlm.nih.gov/pubmed/11793685)
