---
date: 2017-10-23
title: Summary of our LOY paper
tags: ['mypubs']
output: blogdown::html_page
---

## Intro 

### Renal Cell Carcinoma

- [Kidney Cancer: new cases and deaths](https://seer.cancer.gov/statfacts/html/kidrp.html)
	- 8th most common cancer.
	- 64K new cases of kidney cancer each year in US; **15.6 per 100K**; 3.8% of all new cases.
	- 14.4K deaths; 3.9 per 100K; **2.4% of all cancer deaths**.
	- **74.1%** surviving 5 years.
	- 1.6% lifetime risk to be diagnosed.
	- Median age at diagnosis: 64
	- Incidence is increasing but death rate and survival are improving.
- Kidney cancer incidence rates are **highest in Europe, North America, and Australia** and lowest in India, Japan, Africa, and China. [ref.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3930658/)
- Cigarette **smoking** is a risk factor and associated with cancer stage.
- Increased **BMI** is an independent risk factor for RCC.
- **Hypertension** doubles the risk of RCC.
- RCC represents 85-95% of all adult kidney cancer. [ref.](http://www.clevelandclinicmeded.com/medicalpubs/diseasemanagement/nephrology/renal-cell-carcinoma/)

### Clear cell RCC

- 60–80% of RCC.
- **loss of chromosome 3p** in about 90% of the sporadic cases.
- **VHL**, *PBRM1*, *SETD2*, and *BAP1*, mutated in 80%, 40%, 19% and 12% of cases.

> Inactivation of VHL leads to constitutive stabilization of the hypoxia inducible transcription factors (HIF), and abnormal activation of their downstream genes, which contribute to cancer development. The remaining three genes encode proteins involved in chromatin remodeling and histone modifications, highlighting the important role of epigenome aberration in the disease.


## KDM5D & KDM6C

Why them ?

1. Their X-linked homologs involved in ccRCC.
1. Epigenetic factors and 3 out the 4 most hypermutated genes are too (PBRM1, SETD2 and BAP1).
1. Deletion of KDM5D has been detected in 52% of prostate cancers.


**KDM5D** encodes a lysine-specific **histone H3 demethylase**, which plays an important role in epigenetic regulation. 
Its down-regulation could have a functional impact because:

- Knockdown of KDM5D through RNA-interference (RNAi) increases cell proliferation and reduces apoptosis in prostate cancer, suggesting a tumor suppressor function for this gene.
- 85% similar and same functions as KDM5C (chr X), which is recurrently mutated in ccRCC.
- KDM5C is recurrently mutated in ccRCC and its inactivation leads to genomic instability in ccRCC through deregulation of H3K4 methylation.

**KDM6C demethylates H3K27**.

- 83% similar and similar function as KDM6A (chr X), which is recurrently mutated in ccRCC.
- KDM6A is recurrently mutated in ccRCC.

We tested whether **KDM5D expression has an anti-tumor activity** in renal cancer:

- Compared RCC cell lines from male patients and selected the one with no KDM5D expression (likely LOY).
- Ectopic expression of KDM5D reduced cell viability to 65%.

Other candidates: 

1. TMSB4Y has recently been identified as a tumor suppressor gene downregulated in male breast cancers16, but not connected to ccRCC.
