---
title: Epilepsy genes candidates
date: 2017-10-02
tags: ['literature']
output: blogdown::html_page
---

We had a few candidate genes that could be affected by non-coding CNVs.
We could try to recreate the deletions using CRISPR but we need to know the cell type to phenotype (and how/what to phenotype).
I'll try to find information from the various databases and from publication.

Our collaborators can differentiate cells into **glutamatergic** neurons (as opposed to *GABA-ergic*).
For the phenotype, we could monitor the gene expression levels.
It's an intermediate phenotype but could be convincing enough.
Otherwise, Knut mentioned *"neural network effects such as Ca++ flux"*.

## Candidate genes

- SZT2, DNM1, MRS2, KCTD7, ST3GAL3, CELSR1, CACNA1A for the CNVs in unique regions.
- SERPINI1, SCN2A, SCN1A, CPA6, BRAF, WWOX, MMP27, N6AMT1, MYO3A, HCN1, SCN5A, CLN6, EPM2A, FAM63B for the CNV in unique regions.

## Glutamatergic?

Simply means "related to glutamate". 
Ok, that was easy, next...

*Glutamate?* **Glutamate** or glutamic acid is an amino acid.
In our case I think we are more interested in its role as a neurotransmitter.
The **most abundant neurotransmitter** (90% of human brain connections).
Glutamate binds and activates receptors (AMPA, kainate, NMDA) that in turn open membrane channels that let ions pass through.

In **some diseases an excess of glutamate** can lead to cell death when its transporters are not effectively removing it from the extracellular space.
This type of glutamate excess has been observed in strokes, autism, ID, AD and **epilepsy**.

In epilepsy, an epileptic phenotype could be recreated though micro-injection of glutamate.
It caused a **depolarization** that can become stronger with some kind of feedback loop.

## KCTD7

Two brothers with a severe form of **epilepsy** showed the **excess of glutamine** ([ref.](https://www.ncbi.nlm.nih.gov/pubmed/27742667)).
From exome sequencing they found a frame-shift mutation in KCTD7 and performed some experiments in animal models.

> [...] KCTD7 has an impact on K+ fluxes, neurotransmitter synthesis and neuronal function, and that malfunction of the encoded protein may lead to progressive myoclonus epilepsy.

The non-coding CNV we found was located downstream of the gene in an active and conserved region. 
It overlaps an eQTL associated with the gene's expression.

## SZT2

Also called "Transcript increased in **glutamate** resistance" because it was *"upregulated in resistance to oxidative glutamate toxicity"* ([ref.](https://www.ncbi.nlm.nih.gov/pubmed/20045724)).

> [...] oxidative glutamate toxicity and excitotoxicity are plausible mechanisms underlying epileptogenesis caused by SZT2 mutations.

[Ref](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3769928/)

The non-coding CNV we found was located downstream of the gene, overlapping a DNase site associated with the gene.

## HCN1

> HCN1 channels selectively regulate glutamatergic synaptic release.

> HCN channels inhibit glutamate synaptic release by suppressing the activity of low threshold voltage-gated T- (CaV3.2) type Ca2+ channels

> HCN1 channels are predominantly located at glutamatergic synaptic terminals

from [Ref](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3068302/)

Also glutamate levels affect HCN1 trafficking ([ref.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2863223/))

The non-coding CNV was an intronic deletion. 
Not confirmed but with a clear coverage drop. 
It overlaps an eQTL.

## CACNA1A

Not much except it seems like an important epilepsy gene that may involve glutamatergic neurons and other types of mechanisms. 
Pathways from ByoSystems: Glutamatergic synapse (but also GABAergic synapse).

## SCN1A

Dravet syndrome. 

## CPA6

Knockdown lead to downregulation of glutamate transporters ([ref.](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0152905)).

## EPM2A

Something about EPM2A- mice and how active-caspase-3 appears only in glutamatergic neurons ([ref.](https://molecularbrain.biomedcentral.com/articles/10.1186/1756-6606-7-7)).

> [...] homeostasis of glutamate transporter GLT-1, called EAAT2 (Excitatory AminoAcid Transporter 2) in humans, is affected in mouse primary astrocytes lacking either EPM2A or EPM2B genes.

[Ref](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5472677/)

## N6AMT1

Something about Glutamine Methyltransferase but not related to the neurotransmitter I think.

## MRS2, ST3GAL3, CELSR1, SERPINI1, SCN2A, BRAF, WWOX, MMP27, MYO3A, SCN5A, CLN6, FAM63B

Nothing much.

## DNM1

[Asinof et al.](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005347) says the epilepsy phenotype comes from GABA neurons and other phenotypes (ID) from glutamatergic neurons.
