---
date: 2017-01-14
title: The Self-Assessment Trap
tags: ['literature']
output: blogdown::html_page
---

I just read a short correspondence about the self-assessment trap, i.e. when **the author is the judge, jury and executioner** of comparing his method against existing methods. 
One visible outcome is that most methods are found to be the *best*, which is unlikely to be true.

A typical explanation for this bias is the selection by the authors of just the metrics in which their method is better. 
Different aspects of the same problem are emphasized in different papers and used for benchmarking.

Sometimes it is difficult to benchmark methods, especially in biological sciences. 
The data is too small, or the expectation is not completely clear, or the experimental validation is partial or too unreliable.

They propose a few guidelines to avoid this trap:

-  Use third-party validation and previously unseen data.
-  Use more than one metric to evaluate the methods.
-  Report good methods even if not the best.
-  Stress the impartial assessment to editors/reviewers.
-  Change scientific culture to value follow-up studies to confirm/refute results.

They then mention some initiatives ([DREAM](http://www.the-dream-project.org), [CASP](http://predictioncenter.org/) or [CAPRI](http://www.ebi.ac.uk/msd-srv/capri/)) that address at least the first 3-4 guidelines.

Source: [The self-assessment trap: can we all be better than average? by Norel et al.](http://www.pubmedcentral.nih.gov/articlerender.fcgi?artid=PMC3261704)
