---
date: 2017-10-19
title: Lit Digest - Testing overlap between genomic regions
tags: ['literature']
output: blogdown::html_page
---

## LOLA: enrichment analysis for genomic region sets and regulatory elements in R and Bioconductor 

[Sheffield 2015](https://academic.oup.com/bioinformatics/article-lookup/doi/10.1093/bioinformatics/btv612)

- Expanding on the gene-centric enrichment analyses.
- The [R package](http://bioconductor.org/packages/LOLA/) efficiently tests for significant overlap (Fisher test) and report results.
- The user specify the *universe*, i.e. all the regions that could have been selected.
- To test enrichment in differential-like analysis where a subset of regions is tested for overlap.
- Not directly feasible for CNVs expect if we provide a set of control regions as *universe*.

## Exploring massive, genome scale datasets with the GenometriCorr package.

[Favorov 2012](https://www.ncbi.nlm.nih.gov/pubmed/22693437)

> R package that efficiently calculates the spatial correlation between two sets of genomic intervals.

## Genome-wide study of correlations between genomic features and their relationship with the regulation of gene expression.

[Kravatsky 2015](https://www.ncbi.nlm.nih.gov/pubmed/25627242)

> We developed the criteria for the assessment of genome track inhomogeneity and correlations between two genome tracks.
