---
date: 2018-03-31
title: SV-eQTLs in GTEx data from WGS
slug: chiang-sveqtl-2017
tags: ['literature']
output: blogdown::html_page
---

This is a review of "*The impact of structural variation on human gene expression*" ([Chiang Nat Gen 2017](http://www.pubmedcentral.nih.gov/articlerender.fcgi?artid=PMC5406250)) from the Hall lab.

## Summary

Using **deep WGS** from 147 individuals in **GTEx** they called **SVs and eQTLs** across 13 tissues (RNA-seq).
For the first time they could investigate the contribution of small SVs in gene expression changes, comparing it with SNVs and indels.
They estimated that **3.5-6.8% of eQTLs are caused by SVs** and that SVs tend to have a larger effect size.
Most causal SVs were **non-coding** and were **enriched** in or close to **regulatory regions**.
They also detected an enrichment of rare SVs close to genes with outlier expressions, suggesting that rare SVs could have a high-impact on gene expression.

## Methods

- WGS ~50x
	1. SpeedSeq pipeline: BWA-MEM + LUMPY.
	1. SVtyper to genotype the population.
	1. Genome STRiP to detect additional CNVs.
	1. QC included: homogeneous number across samples, similar frequency distribution, array-based intensity rank-sum (IRS) statistics.
- RNA-seq from GTEx across 13 tissues.
- eQTL detection with FastQTL
	1. SV-only for SVs with MAF>.05 and 1 Mbp cis window.
	1. SNV/indels/SV joint-calling
- Causal variant in eGene
	1. Highest P-value.
	1. CAVIAR (signal magnitude and direction + LD structure).
	1. Heritability of the top SV vs 1000 top SNVs using a linear mixed model.
- Causal non-coding SV characterization.
	- Grouping the SV-eQTLs by "causality score" (CAVIAR + heritability).
	- Overlap with regulatory region: TSS, enhancers, gene 3' end, TAD.
	- Sometimes adds 10 Kbp flanks to annotation.
- GWAS comparison
	1. Subset of high-confidence GWAS SNVs.
	1. Overlap with lead eQTL from joint analysis.
	1. Subset where SV was the lead eQTL.
- Rare SVs effect
	1. Identify gene expression outliers.
	1. Identify rare SVs (at most two individuals).
	1. Test enrichment in gene body + 5 Kbp.

## Results

- SV catalog: deletions (50.7%), duplications (15.0%), multiallelic CNVs (mCNVs; 6.5%), reference mobile-element insertions (rMEIs; 8.7%), inversions (0.2%) and breakends (BND; 18.9%).
- **11% of SV-eQTLs were exonic** in the SV-only analysis, the majority of which followed the expected gene change.
- The joint eQTL calling identified 23.5K eQTLs: 85.55 SNVs, 10.9% indels, *3.5% SVs*.
- **3.5%** of eQTLs were the identified as **causal by CAVIAR**.
- In **6.8%** of eQTLs, the **heritability** of gene expression due to the top SV was higher that the one due to the additive effect of the 1K top SNVs.
- The median effect size on gene expression was 1.3 times larger for SVs than SNVs and indels.

The most **causal SV-eQTLs were enriched in** mCNVs and duplications, exons (from the eGene), enhancers, TFBS, 10 Kbp upstream or downstream of the eGenes (TSS or 3' end).

**Only 58.2%** of common autosomal **SVs were in strong LD** (r-squared>0.8) with a SNV or indel in the WGS data.
To further stress the value of WGS and SVs, they estimated that only 3.8% of common CNVs were detectable on the Omni 2.5 SNP-array platform.

While rare variants were in general 1.2-fold **enriched in gene body (+-5 Kbp)**, the enrichment was much stronger for **rare SVs** (**16.1-fold**).
Rare SVs close to expression outliers were significantly larger and duplications more frequent.
Around 80% of these SVs were CNVs altering gene dosage; ~11% were non-coding CNVs; A few were complex SVs.

## For future inspiration

- What is this **IRS** (intensity rank-sum) statistics that they use as validation? Is it just how concordant the calls are with array signal. If so, isn't it validating only large CNVs?
- How does BEDtools shuffle regions?

## Clever analysis

Comparing the direction of the gene expression changes per SV class (exonic or not) to suggest that they are indeed causal.

## Questions

- Not sure I understand Fig 3a completely. If the x-axis represent classes of SVs based on the quantile of the causality score, shouldn't all the decile classes have the same number of SVs (y-axis)? And shouldn't they  be one fifth of the first bar that represent the 0-0.5 quantile?
- They show that the MAF is similar in SNVs, indels and SVs. Shouldn't it be driven by the variant size? Wouldn't we expect large deletions to be less frequent than SNVs in general?

## References

- The SVs paper from the 1000GP (Sudmant et al 2015) had tested SNV-SV eQTLs in lymphoblastoid cell lines and found 54 eQTLs (0.56%) with a lead SV-eQTL.
- [Dragon ENhancers database (DENdb)](http://www.cbrc.kaust.edu.sa/dendb/).
- [FunSeq](http://archive.gersteinlab.org/funseq2.1.0_data/) from the Gerstein lab (see Fu et al. FunSeq2 Genome Biol 2014).
