---
date: 2019-02-12
title: "Minimizers, CNV burden, and ref-guided scaffolding"
tags: ['literature']
output: blogdown::html_page
---

I accumulated a huge number of articles in Feedly and I don't know what to do about them. 
One thing I decided to try was to go over them quickly and write down what I want to remember.
I don't think I will read these kind of posts again but maybe it will help me remember or eventually find the reference again.

### Minimizer indexes

I would like to understand better minimizer indexes as they seem to be more and more important in the field.
A [recent preprint](https://www.biorxiv.org/content/10.1101/546309v1?rss=1) introduces the three ways to index kmers: 

1. index fixed-size words in sets (e.g. Bloom filters)
2. full-text index (e.g. FM-indexes)
3. generic associative indexes (~hash tables).

With Bloom filters we can test if a kmers is probably in a set or if it is not. 
So there can be false-positives but no false-negatives.
It requires much less memory than a more naive indexation.
A Bloom filter is basically a bit array and some hash functions that map to the bit array. 
To add an element it is passed to each hash function and the resulting bits turned on.
To test if an element is in the Bloom filter we can just use the hash functions again and test if all the bits are on.
When this occurs by chance, it's a false-positive.
Elements cannot be removed from a Bloom filter.
Query time is constant.

FM-indexes uses Burrows-Wheeler transform to compress a text while still allowing fast substring search.
The name comes from *Full-text index in Minute space*.
Query time as well as space is sublinear.

Another approach is described in a [post from Adam Phillipy](https://genomeinformatics.github.io/mashmap/).
He describes an approach for *approximate* mapping which might be better suited than traditional approaches when mapping long reads with higher error rates.
The basic idea is to extract a kmer from a string, for example the smallest according to an defined order.
In practice a window slides over a long string/reads and saves the minimizers in each window.
The minimizers are used to quickly find hits in the genome.
They can also be used to estimate the identity of the read alignment, avoiding a costly realignment step.
[Minimap2](https://github.com/lh3/minimap2), developed by Heng Li, is also using minimizer indexes to find seeds for its seed-chain-align strategy.

### Phenome-wide burden of copy number variation in UK Biobank

[bioRxiv](https://www.biorxiv.org/content/10.1101/545996v1?rss=1)

CNVs genotyped from arrays across almost 500M individuals using PennCNV.
The average size of the ~300K CNVs was 226 kbp.
Because individuals in the cohort are relatively healthy (enrolled at age 40-69), they used this data to create a CNV intolerance score similar to the CNV pLI from the ExAC project.
They describe in more details associations with coronary artery disease and body mas index, including some in intergenic regions.

### Fast and accurate reference-guided scaffolding of draft genomes

[bioRxiv](https://www.biorxiv.org/content/10.1101/519637v1)

From the Schatz lab, RaGOO that uses minimap2 alignment to a reference to produce chromosome-level scaffold quickly.
It also identifies structural variants and can correct for apparent chimeric contigs.
The algorithm is basically three steps: 

1. aligning with minimap
2. clustering contigs
3. ordering and orienting contigs.

Chimeric contigs can be inter-chromosomal or intra-chromosomal.
Large portions of an intra-chromosomal chimeric contigs will map uniquely to at least two distinct reference chromosomes.
A similar approach is used for intra-chromosomal chimeric contigs, using a user-defined maximum distance (default is 2 Mbp).
[RaGOO](https://github.com/malonge/RaGOO) is written in Python.


