---
date: 2021-03-03
title: "Skim"
tags: ['literature', 'sv']
bibliography: [../../library-small.bib]
link-citations: true
output: blogdown::html_page
---

## Copy number variation (CNV) identification, interpretation, and database from Brazilian patients

[Genet Mol Biol. 2020](https://pubmed.ncbi.nlm.nih.gov/33306777/)

- adress lack of diversity in genomics study thanks to diverse/admixed Brazilian population.
- Methods
  - 268 clinical samples, inc. neurodev disorders and/or congenital malformations.
  - microarrays. SVs> 50 probes and >150-200 kbp
  - annotation with DGV, DEVIPHER, ClinVar, ClinGen, RefSeq genes. ACMG guidelines
  - pathogenic if not in DGV (>=3 individuals and >50% coverage) and: >3Mb; or known; or OMIM gene + DECIPHER/ClinVar/ClinGen + phenotype match
- Results: more frequent CNVs in their dataset compared to open resources (which?)
- 2.7% of 1,504 autosomal CNVs classified as pathogenic using gene content and overlaps with known clinical CNVs.

Some regions were frequently affected (4 in particular), more than in other studies on European samples for example.
This results is used to suggest that more diverse population shows a better picture of the variant distribution in the population.
My main concern is that this sample set was specifically selected for NDD and other disease phenotypes while they compare to the frequencies in studies on "healthy" populations.

Read next:
- ACMG guidelines

## Epigenomic differences in the human and chimpanzee genomes are associated with structural variation

[Genome Research 2021](http://www.genome.org/cgi/doi/10.1101/gr.263491.120)

Between human and chimp, 20-50k bp indels co-occur with epigenomic differences?

- Epigenomic data/Putative regulatory and repressed regions (PRRs)?
  - put. promoters (H3K4me3), put. enhancers (H3K27ac), H3K9me3 (heterochromatin, "repressed")
  - Cell types: cranial crest cells?
- Lineage bias in epi-marks based on peak calls and read difference (ChIP-seq)
  - Peaks are compared with OrthoINDEL which lifts indel-containing regions better.
- Insertions/deletions: DASVC
  - Select non-repeat ones with ancestral state (gorilla outgroup)
- 12% of indels overlap 
  - 15% of these associated with lineage-biased PRRs
- PRRs with indels more likely to be lineage-biased (1.3-3x)
  - insertions in human tend to result in more human-biased, and inversely for deletions (same for chimp)
- Enrichment of 20-50 bp indels in CpG islands around promoters
  - More than in promoters without CpG. I imagine because CpG islands are more prone to slippage-like variation?
- Examples of transposable elements insertions that lead to new regulatory regions
  - SVAs in CNCC correlated with NR2F1 binding (nice motif  found too)
  - LTR5 in iPSC
