---
sidebar: true
title: Genome Assembly
bibliography: [../../static/library-small.bib]
link-citations: true
weight: 5
output:
  blogdown::html_page:
    toc: true
---

# Human *de novo* assembly

## One technology

## Hybrid approach combining technologies

In order to construct a *de novo* assembly a Korean human genome, @Seo2016 used Pacbio (101x), BioNano (97x+108x), Illumina (72x), 10X linked-reads (30x) and BAC libraries.
They achieved a contig N50 of 17.9 Mb and a scaffold N50 of 44.8 Mb.
Of note, they managed to close 105 and extends 72 out of the 190 euchromatic gaps in the reference genome.
Using the short, long, linked and BAC sequences, they phased the genome with the final phased block having a N50 of 11.6 Mb.
With their assembly they identified 18,120 SVs, many which had never been reported but are observed in the Asian population.
They then aligned raw reads from the 1000GP and other Asian WGS samples to investigate the frequency of the insertions of new unique sequence (not TE I guess).
~800 were found in all the ancestral groups and concluded to be fixed (and should be included in the reference genome.
400 insertions showed polymorphic frequency and 76 were Asian-specific.
`It's strange that they don't use some primate genomes to assess the ancestral state of these regions: it might well be deletion in the rest of the population rather than insertion, especially when flanked by duplications.`

In @Maretty2017, 50 Danish trios were sequenced and *de novo* assembled.
A mixture of short-reads and  mate-pairs library totaled ~78x depth per genome.
They used Allpaths-LG assembler and obtained a median N50 of ~21 Mbp.
They were happy with the quality of their assembly:

> We conclude that the contiguity of our assemblies is similar to the long-read assembly and second only to the reference genome and the de novo assembly of a hydatidiform haploid mole

Variant calling was performed by aligning reads on the reference genome to produce SNVs/indels candidates and on the assembled genome to produce non-SNV candidates.
The candidates variants were pooled together and genotyped by BayesTyper which uses khmers from raw reads and a variant graphs.
They found viral integration, SNVs, indels and SVs, many of which were novel compared to 1KGP and dbSNP.
They further re-genotyped NA12878 for their variants and found more than 8 thousands of the novel SVs there.
Using their trios they showed that the rate of *de novo* mutation is correlated with paternal age, as was shown before.
They continue with a detailed analysis of the MHC region.
Finally they show that their data can be used to improve imputation and GWAS.


- Single haplotype assembly of the human genome from a hydatidiform mole
- [Genome Research 2014](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4248323/)
- 100x Illumina, BAC.
- Reference-guided assembly.
- Comparison with other assemblies.
- Repeat content, gene annotation.
- Risk alleles.
- Segmental duplication, comparison with GCRh37.
- Assembly quality: het SNV, BAC ends, Pacbio reads.


- Assembly and diploid architecture of an individual human genome via single-molecule technologies
- [Nature Methods 2015](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4646949/)
- CEPH12878 Illumina assembly improved with PacBio and Bionano.
- Assembly quality.
- SNV detection and phasing.
- Comparison with hg19: large variants.
- Complex variants, e.g. SVs and tandem repeats.


## Telomere to telomere assemblies

@Miga2020 assembled the haploid hydatidiform mole CHM13 using multiple technologies, including ultra-long read nanopore sequencing.
The Canu assembly combined ~40x of ultra-long nanopore reads and ~70x of PacBio reads.
The assembly was polished using multiple technology from longest to shortest: Nanopore, Pacbio, linked-read Illumina.
The final accuracy was, on average, 99.99%
Their assembly is better than GRCh38 in term of contiguity: 75Mb vs 56Mb contig NG50.
The most impressive feat is their manual assembly of chromosome X's centromere.
Chromosome X was chosen because of the quality of the original assembly, its well-known centromere structure, and its importance for traits and Mendelian diseases.
For the two segmental duplications resolved manually, they simply identified ultra-long reads spanning the repeats.
For the centromere they first identified a catalog of variants (SVs and SNVs) that could differentiates the different higher-order repeats.
Using these "signposts", long reads could be tiled and later used for polishing.
It's the same approach as what they used for chromosome Y earlier [@Jain2018a].
The nanopore sequencing was also used to look at methylation patterns, including a drop of methylation in a short region in multiple centromeres.
Of note, their assembly leads to more balanced deletion/insertion ratio when used as reference, while GRCh38 is biased toward more insertions (pointing at a deletion bias in the reference genome).


# Sequencing of one individual to improve reference genome

## Assembly

@Takayama2019 sequenced 3 Japanese individuals using high depth PacBio, Bionano and short read sequencing to create a better reference genome for the Japanese population, JG1.
They made a meta-assembly, merging the 3 de novo assemblies and, when possible, picked the major allele across the 3 individuals.
They show that JG1 reduces the number of variants, including the number of false positives, while still detecting important disease-causing SNVs.


## Short read sequencing

- [The Qatar genome: a population-specific tool for precision medicine in the Middle East](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4927697/)

- Haplotype-resolved genome sequencing of a Gujarati Indian individual
- [Nature Biotech 2011](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3116788/)
- Sequencing of haploid subsets 2.4x, Illumina 15x.
- SNV calling and phasing.
- Comparison with HapMap.
- Phasing of some deletions and a few inversions.
- Anchor contigs from published assemblies.
- Example of compound heterozygosity.


- The diploid genome sequence of an Asian individual
- [Nature 2009](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2716080/)
- Han Chinese, Illumina 36x.
- Alignment and assembly.
- SNV, indels, SV.
- Novel variants by comparing with 1KGP and dbSNP.
- SNV quality assessment.
- Compare SNPs with other individual genomes (Venter, Watson).
- Ancestral allele of indels.
- Assembled unmapped reads to find YH-specific sequences.
- Phasing and haplotypes.
- Ancestry analysis with HapMap.
- Disease risk variants.


- Sequencing and analysis of an Irish human genome
- [Genome Biology 2010](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2965383/)
- Illumina 11x.
- SNV, indels.
- Novel variants by comparing with dbSNP.
- SNV calling quality control.
- Novel SNVs in LD with disease-associated variants. Examples and impact prediction.
- Gene duplication under positive selection.
- Population genetics: PCA, Y chr subgroup, mtDNA haplogroup.
- Test imputation quality.
- Haplotype for SNV calling


## Assessing the quality of a *de novo* assembly

- Contiguity: contig N50, scaffold N50.
- Concordance between assembly and BAC end sequences [@Seo2016].


# Bibliography
