---
sidebar: true
title: Structural Variation and Repeats
bibliography: [../../library-small.bib]
link-citations: true
weight: 5
output:
  blogdown::html_page:
    toc: true
---

@De2011a  found an enrichment of somatic CNV breakpoints in simple repeats, Alu and CR1.

# Segmental duplications

Segmental duplications are genomic regions ranging from *1-400 Kbp* present in multiple locations and sharing a **high level (*>90%*) of sequence identity** [@Sharp2006].
Some blocks are duplicated in the same chromosome while others locate in non-homologous chromosomes.
They tend to **cluster around centromeres** and to a lower extent in sub-telomeric regions.
The mechanism responsible for this distribution remains poorly understood.

Segmental duplications seem to be involved in the formation of many large scale genomic rearrangements likely through **NAHR** resulting in deletions, duplications or inversions [@Sharp2006].
They are clearly associated with sites of polymorphic rearrangements.
Segmental duplication are **hot-spots of chromosomal rearrangements** both in polymorphism and between species [@Sharp2006].
Segmental duplication is also the most important predictor of assembly gap location.

When @Cooper2007 looked at the distribution of CNVs in the human genome, they also observed the strong enrichment in segmental duplications.
They focused on large (*>1*Kbp) CNVs and investigated their density in 1-Mb bins.
CNVs location also correlated with exons and mobile elements (e.g. Alu).
They found a more striking effect with young SDs.
CNVs in SD are enriched for genes involved in *sensory response, immune response, cell adhesion and structural proteins*.

More than half of all nucleotides annotated to be within SD overlap with CNVs [@Cooper2007].
Duplicated regions of the genome are enriched 4-10 fold for CNV [@Cooper2007].
~80 of the duplicated genes between two individuals correspond mostly to segmental duplications [@Alkan2009].

Regions composed of numerous high-copy segmental duplication are the **most challenging regions** in normal genomes.
They contain frequent and often complex SV.

Recent segmental duplications have been caused by Alu-mediated NAHR.
Others occurs in DNA regions with decreased helix stability or increased DNA flexibility [@Sharp2006].
In @Zarrei2015 45-60% of nucleotides of segmental duplications overlap a CNV.

# Centromeric/telomeric regions

+ What is known about centel variation in normal genomes ?
+ Are there more de novo CNV/SV near centromere/telomere ?

While developing *DELLY*, @Rausch2012 noticed an **accumulation of putative SV calls in centromeric and telomeric regions**.

Centromere controls chromosome segregation during cell division [@Aldrup-MacDonald2014].
Surprisingly, DNA sequences in centromeres differs between and within organisms, although the protein component of centromeres (centromere proteins CENPs) are shared among species.
In human, repetitive **alpha satellite DNA** defines the centromere [@Aldrup-MacDonald2014].
Centromere identity is specified by epigenetic mechanisms [@Aldrup-MacDonald2014].

Physical and genetic maps of centromere regions were built using pulsed-field gel electrophoresis [@Aldrup-MacDonald2014].
Sequencing approaches are more challenging and require in silico and high-stringency BAC clone screening.

A high proportion of segmental duplications have accumulated in pericentric regions [@Aldrup-MacDonald2014].
@Nguyen2006  found a **significant over-representation of CNVs within 2 Mb of telomeres and centromeres**, based on both aCGH and sequencing calls.

Telomere localizes at the physical ends of linear eukaryotic chromosomes and maintains their stability and integrity [@Bolzan2012].
In vertebrates, **telomeres are composed of *(TTAGGG)n* repeats** which can localize at the terminal regions of chromosomes or at intra-chromosomal sites (interstitial telomeric sequences or ITSs).
ITSs are present at centromeric regions or between the centromere and the telomere.

# Euchromatic variants

**Cytogenetically visible aberrations** occurring at appreciable frequencies are termed euchromatic variant.
Euchromatin is defined as genomic regions with lightly packed chromatin, **highly concentrated in genes and often under active transcription**.
These large euchromatic variants are to be interpreted with cautious because they do involve a large amount of genic material but are also often normally segregating in the population.
Euchromatic variant seem to be the extreme end of CNV distribution.
Although in euchromatin, they locate clearly near pericentromeric regions.


# DNA satellites

+ How is it detected usually ?
+ How variable are they in normal genomes ? In cancer ?
+ What is their size distribution ? How does this vary according to the distance to genes ?

Satellite DNA are **tandem repeated sequences** accounting for *10-15% of all human repetitive sequence*.
The repeat unit (from 1 to hundreds bp) is repeated either in the same (direct repeats) or opposite (inverted repeats) orientation [@Rich2014].
Inverted repeats are rare.
Satellite DNA **preferably locates in telomeric and centromeric regions**.
They can be divided in four classes according to the unit repeat size : **microsatellites (less than 10bp), minisatellites (10-60 bp), (midi)satellites (hundreds bp), macrosatellites (thousands bp)**.

Microsatellites can also be called simple sequence repeats (SSR) or short tandem repeats (STR).
They are highly instable, hence good genetic markers.
Hereditary nonpolyposis colorectal cancer (HNPCC), also known as Lynch syndrome, is a common autosomal dominant syndrome characterized by microsatellite instability (MSI).

The majority of minisatellites are GC-rich.
It contains the hyper-mutable repeats which are flanked by double strand breaks hot spots and show high rate of meiotic instability.
Minisatellites are used in forensic for DNA fingerprinting.

Little is known about of the midisatellites.
They are mostly located in telomeric or centromeric regions and represented by \\(\alpha\\), \\(\beta\\) and \\(\gamma\\)-satellites.
For example, alpha-satellite repeats (ASR), in centromeres, play an important role in chromosome segregation.

**Alpha satellites** have emerged as a paradigm for understanding the genomic organization of tandem DNA [@Warburton2008].
Their repeat unit consists of *171 bp monomers*, found in large highly homologous  arrays at the centromeres of all human chromosomes.
It is though that the majority of alpha satellite DNA remains unassembled and is represented by megabase sized centromeric gaps [@Warburton2008].
**Human centromeres** are located at repetitive alpha satellite DNA arrays [@Aldrup-MacDonald2014].
They compose around 5% of the human genome.
Alpha satellite compose the sequence of most primate centromeres.
An alpha satellite array can span from 250 to 5,000 kb [@Aldrup-MacDonald2014].
Some arrays are composed of higher order repeat units (HORs).
Variation within the alpha satellite is common and complex.
Outside of the higher order arrays, monomers are randomly arranged and span the region between homogeneous array and the chromosome arm [@Aldrup-MacDonald2014].
Alpha satellite arrays tend to be *chromosome-specific*.
Experiments showed that alpha satellites were the minimal sequence necessary for centromere function; and HOR alpha satellites are a substrate for de novo centromere assembly [@Aldrup-MacDonald2014].

**Satellites II and III** are the most abundant tandem repeats in the human genome after alpha satellites [@Warburton2008].
Satellite III is composed of pentameric sequence *GAATGn* (and reversed *CATTCn*).
The size of these tandem repeats can reach 100 kb.
Satellite II is based on highly diverged arrays of *GAATG* [@Warburton2008].
These two satellites families are found in the pericentromeric regions of many human chromosomes, as well as heterochomatic blocks.

**Centromeric Repeats (CER)** are based on a 48 bp repeat and also found in some centromeric regions.

Gamma satellites (GSAT) are highly diverged relatively GC rich ~200 bp tandem repeat.

Macrosatellites repeats (MSR) can contain ORF.

In cancer *Breaking of satellites' silence* is a **paradigm in cancerogenesis**[@Rich2014].
In cancer satellites are hypomethylated and are thought to induce peri-centromeric instability.
This might explain the observed over-expression of satellite repeats in tumors.

For example, @Ting2011  observed a **40-fold increase in pericentromeric satellites expression in pancreatic ductal adenocarcinomas**.
Alpha satellites were the most abundant, HSATII highly specific to cancer.
The satellite expression also *correlated with L1 expression*.
The hypothesis is an alteration of the silencing mechanisms of these repeats.


# Transposable elements

+ What types of transposable elements get activated in cancer ?
+ Which TEs are known substrate for NAHR ?
+ Any inactive transposons causing SVs ?
+ Where does the different families come from ? Virus only ?


Large SVs caused by TE insertion Interested in disease-causing CNVs with non-recurrent breakpoints, @Vogt2014  noticed some SVA insertions in some of the breakpoints.
These insertions could not be validated using classic PCR approaches, they had to use a more complex experiment to deal with the GC-rich sequence of the breakpoint.
Moreover, these insertions seems to be postzygotic somatic events.

## In cancers

L1 retro-transposition is a **common phenomenon** in some cancer, e.g. **epithelial tumors**.
However the assumption is that they become active once the cancer is initiated, thanks to derepression in the tumor tissue.
Hence they are not believed to initiate tumorigenesis but could contribute to the tumor progression and metastasis.

@Tubio2014  performed a survey of **somatic L1 activity across 12 cancer types**, focusing on the **transduction** of flanking sequences.
Around 50% of the tumors had at least one somatic L1 insertion.
Somatic retro-transposition was **most frequent in colon cancer (93%) and lung cancer (75%)**.
They found that 24% of events presented 3' transduction, **half** of which were **orphan transduction** (no L1 sequence inserted).
The size of the transduction was typically less than 1 kb but some were up to 12 kb.
They identified 72 of **'hot' L1 sources** that contributed to more than 95% of the somatic insertions.
Most of these were not known to be hot and are likely intact L1 with **low frequency in human populations**.
Four hot L1 produced 50% of all the transducted insertions.
In the tumors, these hot L1 tended to be **hypomethylated**.
They even observed **sequential retro-transposition** where a L1 jumps somewhere, then jumps again (then jumps again), taking with it part of the second (and third) region as transducted sequence.
This opens up new ways for a L1 insertion to bring regulation changes in a new insertion: it could jump once, grab a regulatory region, jump again and activate another region.
Still, they found no insertion with functional potential. For example, none of the genes with insertion were disregulated, nor expressing aberrant RNA.
Most of the insertions located in gene-poor regions.
Hence they concluded that the vast majority of somatic L1 insertion are **passenger variants**.

In more recent study by @Scott2016, a **driver somatic L1 insertion** in the APC gene contributed to the formation of **colorectal cancer** as the first of the classic two-hits mechanism.
The patient had a subtype of colorectal cancer (MSS) which is **known to start with the disruption of the APC gene**.
The insertion is located in the known mutation hotspot in exon 16 and there is a second hit (premature stop codon) in the other allele.
Both variants were validated and confirmed to be somatic and on different alleles.
They managed to identify the **sources** of this and other insertions and it ended up being **heterozygous L1s absent from the reference genome**.
Using the 1000 Genomes project MEI dataset they show that these hot L1s are present in **african-descent** genomes.
This suggest that the distribution of germline L1 across population might affect the risk to develop cancer (to a certain extent).
Finally they show the the promoter regions was hypomethylated in both the normal and tumor, maybe because of a SNP in one CpG.
In contrast to these hot L1s, other germline L1s were not expressed.

Another example from Shukla et al (2013) shows a **somatic L1 insertion associated with the upregulation of the ST18 gene in hepatocellular carcinoma**.
Apparently the insertion disrupted a repressor region in one of the gene's intron.



# Bibliography
